#!/bin/sh
#
# QiPki build wrapper script
#
# Call qipki-build --help to get help
#

set -e
if [ -z ${QIPKI_BASEDIR} ] ; then
    ## resolve links - $0 may be a symlink
    PRG="$0"
    while [ -h "$PRG" ] ; do
      ls=`ls -ld "$PRG"`
      link=`expr "$ls" : '.*-> \(.*\)$'`
      if expr "$link" : '/.*' > /dev/null; then
        PRG="$link"
      else
        PRG=`dirname "$PRG"`"/$link"
      fi  
    done
    QIPKI_BASEDIR=`dirname "$PRG"`
    # make it fully qualified
    export QIPKI_BASEDIR=`cd "${QIPKI_BASEDIR}/.." && pwd`
fi
/usr/bin/env ruby "${QIPKI_BASEDIR}/scripts/qipki-build.rb" $@
exit 0
